# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/robert/Downloads/Bachelor/Source Code/xdc/Zedboard-Master.xdc

# Block Designs: bd/bachelor/bachelor.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bachelor || ORIG_REF_NAME==bachelor} -quiet] -quiet

# IP: bd/bachelor/ip/bachelor_MATRIX_VECTOR_0_1/bachelor_MATRIX_VECTOR_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bachelor_MATRIX_VECTOR_0_1 || ORIG_REF_NAME==bachelor_MATRIX_VECTOR_0_1} -quiet] -quiet

# IP: bd/bachelor/ip/bachelor_vio_0_1/bachelor_vio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bachelor_vio_0_1 || ORIG_REF_NAME==bachelor_vio_0_1} -quiet] -quiet

# IP: bd/bachelor/ip/bachelor_UART_TRANSMITTER_0_0/bachelor_UART_TRANSMITTER_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bachelor_UART_TRANSMITTER_0_0 || ORIG_REF_NAME==bachelor_UART_TRANSMITTER_0_0} -quiet] -quiet

# XDC: /home/robert/Downloads/Bachelor/Vivado/Vivado.gen/sources_1/bd/bachelor/ip/bachelor_vio_0_1/bachelor_vio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bachelor_vio_0_1 || ORIG_REF_NAME==bachelor_vio_0_1} -quiet] -quiet

# XDC: /home/robert/Downloads/Bachelor/Vivado/Vivado.gen/sources_1/bd/bachelor/bachelor_ooc.xdc
