-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2023.2 (lin64) Build 4029153 Fri Oct 13 20:13:54 MDT 2023
-- Date        : Mon May 26 01:02:36 2025
-- Host        : arch running 64-bit unknown
-- Command     : write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bachelor_COMBINED_OPERATIONS_0_0_sim_netlist.vhdl
-- Design      : bachelor_COMBINED_OPERATIONS_0_0
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7z020clg484-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  port (
    combined_operations_clock : in STD_LOGIC;
    combined_operations_reset : in STD_LOGIC;
    combined_operations_m_a_btint_a : in STD_LOGIC_VECTOR ( 95 downto 0 );
    combined_operations_m_a_btint_b : in STD_LOGIC_VECTOR ( 95 downto 0 );
    combined_operations_m_a_overflow : in STD_LOGIC_VECTOR ( 23 downto 0 );
    combined_operations_m_b_btint_a : in STD_LOGIC_VECTOR ( 95 downto 0 );
    combined_operations_m_b_btint_b : in STD_LOGIC_VECTOR ( 95 downto 0 );
    combined_operations_m_b_overflow : in STD_LOGIC_VECTOR ( 23 downto 0 );
    combined_operations_v_btint_a : in STD_LOGIC_VECTOR ( 23 downto 0 );
    combined_operations_v_btint_b : in STD_LOGIC_VECTOR ( 23 downto 0 );
    combined_operations_v_overflow : in STD_LOGIC_VECTOR ( 5 downto 0 );
    combined_operations_op : in STD_LOGIC_VECTOR ( 1 downto 0 );
    combined_operations_done : out STD_LOGIC;
    combined_operations_result_u_btint_a : out STD_LOGIC_VECTOR ( 127 downto 0 );
    combined_operations_result_u_btint_b : out STD_LOGIC_VECTOR ( 127 downto 0 );
    combined_operations_result_u_overflow : out STD_LOGIC_VECTOR ( 31 downto 0 );
    combined_operations_result_d_btint_a : out STD_LOGIC_VECTOR ( 127 downto 0 );
    combined_operations_result_d_btint_b : out STD_LOGIC_VECTOR ( 127 downto 0 );
    combined_operations_result_d_overflow : out STD_LOGIC_VECTOR ( 31 downto 0 )
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bachelor_COMBINED_OPERATIONS_0_0,COMBINED_OPERATIONS,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "module_ref";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "COMBINED_OPERATIONS,Vivado 2023.2";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture STRUCTURE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  signal \<const0>\ : STD_LOGIC;
  signal \<const1>\ : STD_LOGIC;
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of combined_operations_clock : signal is "xilinx.com:signal:clock:1.0 combined_operations_clock CLK";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of combined_operations_clock : signal is "XIL_INTERFACENAME combined_operations_clock, ASSOCIATED_RESET combined_operations_reset, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN bachelor_combined_operations_clock_0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of combined_operations_reset : signal is "xilinx.com:signal:reset:1.0 combined_operations_reset RST";
  attribute X_INTERFACE_PARAMETER of combined_operations_reset : signal is "XIL_INTERFACENAME combined_operations_reset, POLARITY ACTIVE_LOW, INSERT_VIP 0";
begin
  combined_operations_done <= \<const1>\;
  combined_operations_result_d_btint_a(127) <= \<const0>\;
  combined_operations_result_d_btint_a(126) <= \<const0>\;
  combined_operations_result_d_btint_a(125) <= \<const0>\;
  combined_operations_result_d_btint_a(124) <= \<const0>\;
  combined_operations_result_d_btint_a(123) <= \<const0>\;
  combined_operations_result_d_btint_a(122) <= \<const0>\;
  combined_operations_result_d_btint_a(121) <= \<const0>\;
  combined_operations_result_d_btint_a(120) <= \<const0>\;
  combined_operations_result_d_btint_a(119) <= \<const0>\;
  combined_operations_result_d_btint_a(118) <= \<const0>\;
  combined_operations_result_d_btint_a(117) <= \<const0>\;
  combined_operations_result_d_btint_a(116) <= \<const0>\;
  combined_operations_result_d_btint_a(115) <= \<const0>\;
  combined_operations_result_d_btint_a(114) <= \<const0>\;
  combined_operations_result_d_btint_a(113) <= \<const0>\;
  combined_operations_result_d_btint_a(112) <= \<const0>\;
  combined_operations_result_d_btint_a(111) <= \<const0>\;
  combined_operations_result_d_btint_a(110) <= \<const0>\;
  combined_operations_result_d_btint_a(109) <= \<const0>\;
  combined_operations_result_d_btint_a(108) <= \<const0>\;
  combined_operations_result_d_btint_a(107) <= \<const0>\;
  combined_operations_result_d_btint_a(106) <= \<const0>\;
  combined_operations_result_d_btint_a(105) <= \<const0>\;
  combined_operations_result_d_btint_a(104) <= \<const0>\;
  combined_operations_result_d_btint_a(103) <= \<const0>\;
  combined_operations_result_d_btint_a(102) <= \<const0>\;
  combined_operations_result_d_btint_a(101) <= \<const0>\;
  combined_operations_result_d_btint_a(100) <= \<const0>\;
  combined_operations_result_d_btint_a(99) <= \<const0>\;
  combined_operations_result_d_btint_a(98) <= \<const0>\;
  combined_operations_result_d_btint_a(97) <= \<const0>\;
  combined_operations_result_d_btint_a(96) <= \<const0>\;
  combined_operations_result_d_btint_a(95) <= \<const0>\;
  combined_operations_result_d_btint_a(94) <= \<const0>\;
  combined_operations_result_d_btint_a(93) <= \<const0>\;
  combined_operations_result_d_btint_a(92) <= \<const0>\;
  combined_operations_result_d_btint_a(91) <= \<const0>\;
  combined_operations_result_d_btint_a(90) <= \<const0>\;
  combined_operations_result_d_btint_a(89) <= \<const0>\;
  combined_operations_result_d_btint_a(88) <= \<const0>\;
  combined_operations_result_d_btint_a(87) <= \<const0>\;
  combined_operations_result_d_btint_a(86) <= \<const0>\;
  combined_operations_result_d_btint_a(85) <= \<const0>\;
  combined_operations_result_d_btint_a(84) <= \<const0>\;
  combined_operations_result_d_btint_a(83) <= \<const0>\;
  combined_operations_result_d_btint_a(82) <= \<const0>\;
  combined_operations_result_d_btint_a(81) <= \<const0>\;
  combined_operations_result_d_btint_a(80) <= \<const0>\;
  combined_operations_result_d_btint_a(79) <= \<const0>\;
  combined_operations_result_d_btint_a(78) <= \<const0>\;
  combined_operations_result_d_btint_a(77) <= \<const0>\;
  combined_operations_result_d_btint_a(76) <= \<const0>\;
  combined_operations_result_d_btint_a(75) <= \<const0>\;
  combined_operations_result_d_btint_a(74) <= \<const0>\;
  combined_operations_result_d_btint_a(73) <= \<const0>\;
  combined_operations_result_d_btint_a(72) <= \<const0>\;
  combined_operations_result_d_btint_a(71) <= \<const0>\;
  combined_operations_result_d_btint_a(70) <= \<const0>\;
  combined_operations_result_d_btint_a(69) <= \<const0>\;
  combined_operations_result_d_btint_a(68) <= \<const0>\;
  combined_operations_result_d_btint_a(67) <= \<const0>\;
  combined_operations_result_d_btint_a(66) <= \<const0>\;
  combined_operations_result_d_btint_a(65) <= \<const0>\;
  combined_operations_result_d_btint_a(64) <= \<const0>\;
  combined_operations_result_d_btint_a(63) <= \<const0>\;
  combined_operations_result_d_btint_a(62) <= \<const0>\;
  combined_operations_result_d_btint_a(61) <= \<const0>\;
  combined_operations_result_d_btint_a(60) <= \<const0>\;
  combined_operations_result_d_btint_a(59) <= \<const0>\;
  combined_operations_result_d_btint_a(58) <= \<const0>\;
  combined_operations_result_d_btint_a(57) <= \<const0>\;
  combined_operations_result_d_btint_a(56) <= \<const0>\;
  combined_operations_result_d_btint_a(55) <= \<const0>\;
  combined_operations_result_d_btint_a(54) <= \<const0>\;
  combined_operations_result_d_btint_a(53) <= \<const0>\;
  combined_operations_result_d_btint_a(52) <= \<const0>\;
  combined_operations_result_d_btint_a(51) <= \<const0>\;
  combined_operations_result_d_btint_a(50) <= \<const0>\;
  combined_operations_result_d_btint_a(49) <= \<const0>\;
  combined_operations_result_d_btint_a(48) <= \<const0>\;
  combined_operations_result_d_btint_a(47) <= \<const0>\;
  combined_operations_result_d_btint_a(46) <= \<const0>\;
  combined_operations_result_d_btint_a(45) <= \<const0>\;
  combined_operations_result_d_btint_a(44) <= \<const0>\;
  combined_operations_result_d_btint_a(43) <= \<const0>\;
  combined_operations_result_d_btint_a(42) <= \<const0>\;
  combined_operations_result_d_btint_a(41) <= \<const0>\;
  combined_operations_result_d_btint_a(40) <= \<const0>\;
  combined_operations_result_d_btint_a(39) <= \<const0>\;
  combined_operations_result_d_btint_a(38) <= \<const0>\;
  combined_operations_result_d_btint_a(37) <= \<const0>\;
  combined_operations_result_d_btint_a(36) <= \<const0>\;
  combined_operations_result_d_btint_a(35) <= \<const0>\;
  combined_operations_result_d_btint_a(34) <= \<const0>\;
  combined_operations_result_d_btint_a(33) <= \<const0>\;
  combined_operations_result_d_btint_a(32) <= \<const0>\;
  combined_operations_result_d_btint_a(31) <= \<const0>\;
  combined_operations_result_d_btint_a(30) <= \<const0>\;
  combined_operations_result_d_btint_a(29) <= \<const0>\;
  combined_operations_result_d_btint_a(28) <= \<const0>\;
  combined_operations_result_d_btint_a(27) <= \<const0>\;
  combined_operations_result_d_btint_a(26) <= \<const0>\;
  combined_operations_result_d_btint_a(25) <= \<const0>\;
  combined_operations_result_d_btint_a(24) <= \<const0>\;
  combined_operations_result_d_btint_a(23) <= \<const0>\;
  combined_operations_result_d_btint_a(22) <= \<const0>\;
  combined_operations_result_d_btint_a(21) <= \<const0>\;
  combined_operations_result_d_btint_a(20) <= \<const0>\;
  combined_operations_result_d_btint_a(19) <= \<const0>\;
  combined_operations_result_d_btint_a(18) <= \<const0>\;
  combined_operations_result_d_btint_a(17) <= \<const0>\;
  combined_operations_result_d_btint_a(16) <= \<const0>\;
  combined_operations_result_d_btint_a(15) <= \<const0>\;
  combined_operations_result_d_btint_a(14) <= \<const0>\;
  combined_operations_result_d_btint_a(13) <= \<const0>\;
  combined_operations_result_d_btint_a(12) <= \<const0>\;
  combined_operations_result_d_btint_a(11) <= \<const0>\;
  combined_operations_result_d_btint_a(10) <= \<const0>\;
  combined_operations_result_d_btint_a(9) <= \<const0>\;
  combined_operations_result_d_btint_a(8) <= \<const0>\;
  combined_operations_result_d_btint_a(7) <= \<const0>\;
  combined_operations_result_d_btint_a(6) <= \<const0>\;
  combined_operations_result_d_btint_a(5) <= \<const0>\;
  combined_operations_result_d_btint_a(4) <= \<const0>\;
  combined_operations_result_d_btint_a(3) <= \<const0>\;
  combined_operations_result_d_btint_a(2) <= \<const0>\;
  combined_operations_result_d_btint_a(1) <= \<const0>\;
  combined_operations_result_d_btint_a(0) <= \<const0>\;
  combined_operations_result_d_btint_b(127) <= \<const0>\;
  combined_operations_result_d_btint_b(126) <= \<const0>\;
  combined_operations_result_d_btint_b(125) <= \<const0>\;
  combined_operations_result_d_btint_b(124) <= \<const0>\;
  combined_operations_result_d_btint_b(123) <= \<const0>\;
  combined_operations_result_d_btint_b(122) <= \<const0>\;
  combined_operations_result_d_btint_b(121) <= \<const0>\;
  combined_operations_result_d_btint_b(120) <= \<const0>\;
  combined_operations_result_d_btint_b(119) <= \<const0>\;
  combined_operations_result_d_btint_b(118) <= \<const0>\;
  combined_operations_result_d_btint_b(117) <= \<const0>\;
  combined_operations_result_d_btint_b(116) <= \<const0>\;
  combined_operations_result_d_btint_b(115) <= \<const0>\;
  combined_operations_result_d_btint_b(114) <= \<const0>\;
  combined_operations_result_d_btint_b(113) <= \<const0>\;
  combined_operations_result_d_btint_b(112) <= \<const0>\;
  combined_operations_result_d_btint_b(111) <= \<const0>\;
  combined_operations_result_d_btint_b(110) <= \<const0>\;
  combined_operations_result_d_btint_b(109) <= \<const0>\;
  combined_operations_result_d_btint_b(108) <= \<const0>\;
  combined_operations_result_d_btint_b(107) <= \<const0>\;
  combined_operations_result_d_btint_b(106) <= \<const0>\;
  combined_operations_result_d_btint_b(105) <= \<const0>\;
  combined_operations_result_d_btint_b(104) <= \<const0>\;
  combined_operations_result_d_btint_b(103) <= \<const0>\;
  combined_operations_result_d_btint_b(102) <= \<const0>\;
  combined_operations_result_d_btint_b(101) <= \<const0>\;
  combined_operations_result_d_btint_b(100) <= \<const0>\;
  combined_operations_result_d_btint_b(99) <= \<const0>\;
  combined_operations_result_d_btint_b(98) <= \<const0>\;
  combined_operations_result_d_btint_b(97) <= \<const0>\;
  combined_operations_result_d_btint_b(96) <= \<const0>\;
  combined_operations_result_d_btint_b(95) <= \<const0>\;
  combined_operations_result_d_btint_b(94) <= \<const0>\;
  combined_operations_result_d_btint_b(93) <= \<const0>\;
  combined_operations_result_d_btint_b(92) <= \<const0>\;
  combined_operations_result_d_btint_b(91) <= \<const0>\;
  combined_operations_result_d_btint_b(90) <= \<const0>\;
  combined_operations_result_d_btint_b(89) <= \<const0>\;
  combined_operations_result_d_btint_b(88) <= \<const0>\;
  combined_operations_result_d_btint_b(87) <= \<const0>\;
  combined_operations_result_d_btint_b(86) <= \<const0>\;
  combined_operations_result_d_btint_b(85) <= \<const0>\;
  combined_operations_result_d_btint_b(84) <= \<const0>\;
  combined_operations_result_d_btint_b(83) <= \<const0>\;
  combined_operations_result_d_btint_b(82) <= \<const0>\;
  combined_operations_result_d_btint_b(81) <= \<const0>\;
  combined_operations_result_d_btint_b(80) <= \<const0>\;
  combined_operations_result_d_btint_b(79) <= \<const0>\;
  combined_operations_result_d_btint_b(78) <= \<const0>\;
  combined_operations_result_d_btint_b(77) <= \<const0>\;
  combined_operations_result_d_btint_b(76) <= \<const0>\;
  combined_operations_result_d_btint_b(75) <= \<const0>\;
  combined_operations_result_d_btint_b(74) <= \<const0>\;
  combined_operations_result_d_btint_b(73) <= \<const0>\;
  combined_operations_result_d_btint_b(72) <= \<const0>\;
  combined_operations_result_d_btint_b(71) <= \<const0>\;
  combined_operations_result_d_btint_b(70) <= \<const0>\;
  combined_operations_result_d_btint_b(69) <= \<const0>\;
  combined_operations_result_d_btint_b(68) <= \<const0>\;
  combined_operations_result_d_btint_b(67) <= \<const0>\;
  combined_operations_result_d_btint_b(66) <= \<const0>\;
  combined_operations_result_d_btint_b(65) <= \<const0>\;
  combined_operations_result_d_btint_b(64) <= \<const0>\;
  combined_operations_result_d_btint_b(63) <= \<const0>\;
  combined_operations_result_d_btint_b(62) <= \<const0>\;
  combined_operations_result_d_btint_b(61) <= \<const0>\;
  combined_operations_result_d_btint_b(60) <= \<const0>\;
  combined_operations_result_d_btint_b(59) <= \<const0>\;
  combined_operations_result_d_btint_b(58) <= \<const0>\;
  combined_operations_result_d_btint_b(57) <= \<const0>\;
  combined_operations_result_d_btint_b(56) <= \<const0>\;
  combined_operations_result_d_btint_b(55) <= \<const0>\;
  combined_operations_result_d_btint_b(54) <= \<const0>\;
  combined_operations_result_d_btint_b(53) <= \<const0>\;
  combined_operations_result_d_btint_b(52) <= \<const0>\;
  combined_operations_result_d_btint_b(51) <= \<const0>\;
  combined_operations_result_d_btint_b(50) <= \<const0>\;
  combined_operations_result_d_btint_b(49) <= \<const0>\;
  combined_operations_result_d_btint_b(48) <= \<const0>\;
  combined_operations_result_d_btint_b(47) <= \<const0>\;
  combined_operations_result_d_btint_b(46) <= \<const0>\;
  combined_operations_result_d_btint_b(45) <= \<const0>\;
  combined_operations_result_d_btint_b(44) <= \<const0>\;
  combined_operations_result_d_btint_b(43) <= \<const0>\;
  combined_operations_result_d_btint_b(42) <= \<const0>\;
  combined_operations_result_d_btint_b(41) <= \<const0>\;
  combined_operations_result_d_btint_b(40) <= \<const0>\;
  combined_operations_result_d_btint_b(39) <= \<const0>\;
  combined_operations_result_d_btint_b(38) <= \<const0>\;
  combined_operations_result_d_btint_b(37) <= \<const0>\;
  combined_operations_result_d_btint_b(36) <= \<const0>\;
  combined_operations_result_d_btint_b(35) <= \<const0>\;
  combined_operations_result_d_btint_b(34) <= \<const0>\;
  combined_operations_result_d_btint_b(33) <= \<const0>\;
  combined_operations_result_d_btint_b(32) <= \<const0>\;
  combined_operations_result_d_btint_b(31) <= \<const0>\;
  combined_operations_result_d_btint_b(30) <= \<const0>\;
  combined_operations_result_d_btint_b(29) <= \<const0>\;
  combined_operations_result_d_btint_b(28) <= \<const0>\;
  combined_operations_result_d_btint_b(27) <= \<const0>\;
  combined_operations_result_d_btint_b(26) <= \<const0>\;
  combined_operations_result_d_btint_b(25) <= \<const0>\;
  combined_operations_result_d_btint_b(24) <= \<const0>\;
  combined_operations_result_d_btint_b(23) <= \<const0>\;
  combined_operations_result_d_btint_b(22) <= \<const0>\;
  combined_operations_result_d_btint_b(21) <= \<const0>\;
  combined_operations_result_d_btint_b(20) <= \<const0>\;
  combined_operations_result_d_btint_b(19) <= \<const0>\;
  combined_operations_result_d_btint_b(18) <= \<const0>\;
  combined_operations_result_d_btint_b(17) <= \<const0>\;
  combined_operations_result_d_btint_b(16) <= \<const0>\;
  combined_operations_result_d_btint_b(15) <= \<const0>\;
  combined_operations_result_d_btint_b(14) <= \<const0>\;
  combined_operations_result_d_btint_b(13) <= \<const0>\;
  combined_operations_result_d_btint_b(12) <= \<const0>\;
  combined_operations_result_d_btint_b(11) <= \<const0>\;
  combined_operations_result_d_btint_b(10) <= \<const0>\;
  combined_operations_result_d_btint_b(9) <= \<const0>\;
  combined_operations_result_d_btint_b(8) <= \<const0>\;
  combined_operations_result_d_btint_b(7) <= \<const0>\;
  combined_operations_result_d_btint_b(6) <= \<const0>\;
  combined_operations_result_d_btint_b(5) <= \<const0>\;
  combined_operations_result_d_btint_b(4) <= \<const0>\;
  combined_operations_result_d_btint_b(3) <= \<const0>\;
  combined_operations_result_d_btint_b(2) <= \<const0>\;
  combined_operations_result_d_btint_b(1) <= \<const0>\;
  combined_operations_result_d_btint_b(0) <= \<const0>\;
  combined_operations_result_d_overflow(31) <= \<const0>\;
  combined_operations_result_d_overflow(30) <= \<const0>\;
  combined_operations_result_d_overflow(29) <= \<const0>\;
  combined_operations_result_d_overflow(28) <= \<const0>\;
  combined_operations_result_d_overflow(27) <= \<const0>\;
  combined_operations_result_d_overflow(26) <= \<const0>\;
  combined_operations_result_d_overflow(25) <= \<const0>\;
  combined_operations_result_d_overflow(24) <= \<const0>\;
  combined_operations_result_d_overflow(23) <= \<const0>\;
  combined_operations_result_d_overflow(22) <= \<const0>\;
  combined_operations_result_d_overflow(21) <= \<const0>\;
  combined_operations_result_d_overflow(20) <= \<const0>\;
  combined_operations_result_d_overflow(19) <= \<const0>\;
  combined_operations_result_d_overflow(18) <= \<const0>\;
  combined_operations_result_d_overflow(17) <= \<const0>\;
  combined_operations_result_d_overflow(16) <= \<const0>\;
  combined_operations_result_d_overflow(15) <= \<const0>\;
  combined_operations_result_d_overflow(14) <= \<const0>\;
  combined_operations_result_d_overflow(13) <= \<const0>\;
  combined_operations_result_d_overflow(12) <= \<const0>\;
  combined_operations_result_d_overflow(11) <= \<const0>\;
  combined_operations_result_d_overflow(10) <= \<const0>\;
  combined_operations_result_d_overflow(9) <= \<const0>\;
  combined_operations_result_d_overflow(8) <= \<const0>\;
  combined_operations_result_d_overflow(7) <= \<const0>\;
  combined_operations_result_d_overflow(6) <= \<const0>\;
  combined_operations_result_d_overflow(5) <= \<const0>\;
  combined_operations_result_d_overflow(4) <= \<const0>\;
  combined_operations_result_d_overflow(3) <= \<const0>\;
  combined_operations_result_d_overflow(2) <= \<const0>\;
  combined_operations_result_d_overflow(1) <= \<const0>\;
  combined_operations_result_d_overflow(0) <= \<const0>\;
  combined_operations_result_u_btint_a(127) <= \<const0>\;
  combined_operations_result_u_btint_a(126) <= \<const0>\;
  combined_operations_result_u_btint_a(125) <= \<const0>\;
  combined_operations_result_u_btint_a(124) <= \<const0>\;
  combined_operations_result_u_btint_a(123) <= \<const0>\;
  combined_operations_result_u_btint_a(122) <= \<const0>\;
  combined_operations_result_u_btint_a(121) <= \<const0>\;
  combined_operations_result_u_btint_a(120) <= \<const0>\;
  combined_operations_result_u_btint_a(119) <= \<const0>\;
  combined_operations_result_u_btint_a(118) <= \<const0>\;
  combined_operations_result_u_btint_a(117) <= \<const0>\;
  combined_operations_result_u_btint_a(116) <= \<const0>\;
  combined_operations_result_u_btint_a(115) <= \<const0>\;
  combined_operations_result_u_btint_a(114) <= \<const0>\;
  combined_operations_result_u_btint_a(113) <= \<const0>\;
  combined_operations_result_u_btint_a(112) <= \<const0>\;
  combined_operations_result_u_btint_a(111) <= \<const0>\;
  combined_operations_result_u_btint_a(110) <= \<const0>\;
  combined_operations_result_u_btint_a(109) <= \<const0>\;
  combined_operations_result_u_btint_a(108) <= \<const0>\;
  combined_operations_result_u_btint_a(107) <= \<const0>\;
  combined_operations_result_u_btint_a(106) <= \<const0>\;
  combined_operations_result_u_btint_a(105) <= \<const0>\;
  combined_operations_result_u_btint_a(104) <= \<const0>\;
  combined_operations_result_u_btint_a(103) <= \<const0>\;
  combined_operations_result_u_btint_a(102) <= \<const0>\;
  combined_operations_result_u_btint_a(101) <= \<const0>\;
  combined_operations_result_u_btint_a(100) <= \<const0>\;
  combined_operations_result_u_btint_a(99) <= \<const0>\;
  combined_operations_result_u_btint_a(98) <= \<const0>\;
  combined_operations_result_u_btint_a(97) <= \<const0>\;
  combined_operations_result_u_btint_a(96) <= \<const0>\;
  combined_operations_result_u_btint_a(95) <= \<const0>\;
  combined_operations_result_u_btint_a(94) <= \<const0>\;
  combined_operations_result_u_btint_a(93) <= \<const0>\;
  combined_operations_result_u_btint_a(92) <= \<const0>\;
  combined_operations_result_u_btint_a(91) <= \<const0>\;
  combined_operations_result_u_btint_a(90) <= \<const0>\;
  combined_operations_result_u_btint_a(89) <= \<const0>\;
  combined_operations_result_u_btint_a(88) <= \<const0>\;
  combined_operations_result_u_btint_a(87) <= \<const0>\;
  combined_operations_result_u_btint_a(86) <= \<const0>\;
  combined_operations_result_u_btint_a(85) <= \<const0>\;
  combined_operations_result_u_btint_a(84) <= \<const0>\;
  combined_operations_result_u_btint_a(83) <= \<const0>\;
  combined_operations_result_u_btint_a(82) <= \<const0>\;
  combined_operations_result_u_btint_a(81) <= \<const0>\;
  combined_operations_result_u_btint_a(80) <= \<const0>\;
  combined_operations_result_u_btint_a(79) <= \<const0>\;
  combined_operations_result_u_btint_a(78) <= \<const0>\;
  combined_operations_result_u_btint_a(77) <= \<const0>\;
  combined_operations_result_u_btint_a(76) <= \<const0>\;
  combined_operations_result_u_btint_a(75) <= \<const0>\;
  combined_operations_result_u_btint_a(74) <= \<const0>\;
  combined_operations_result_u_btint_a(73) <= \<const0>\;
  combined_operations_result_u_btint_a(72) <= \<const0>\;
  combined_operations_result_u_btint_a(71) <= \<const0>\;
  combined_operations_result_u_btint_a(70) <= \<const0>\;
  combined_operations_result_u_btint_a(69) <= \<const0>\;
  combined_operations_result_u_btint_a(68) <= \<const0>\;
  combined_operations_result_u_btint_a(67) <= \<const0>\;
  combined_operations_result_u_btint_a(66) <= \<const0>\;
  combined_operations_result_u_btint_a(65) <= \<const0>\;
  combined_operations_result_u_btint_a(64) <= \<const0>\;
  combined_operations_result_u_btint_a(63) <= \<const0>\;
  combined_operations_result_u_btint_a(62) <= \<const0>\;
  combined_operations_result_u_btint_a(61) <= \<const0>\;
  combined_operations_result_u_btint_a(60) <= \<const0>\;
  combined_operations_result_u_btint_a(59) <= \<const0>\;
  combined_operations_result_u_btint_a(58) <= \<const0>\;
  combined_operations_result_u_btint_a(57) <= \<const0>\;
  combined_operations_result_u_btint_a(56) <= \<const0>\;
  combined_operations_result_u_btint_a(55) <= \<const0>\;
  combined_operations_result_u_btint_a(54) <= \<const0>\;
  combined_operations_result_u_btint_a(53) <= \<const0>\;
  combined_operations_result_u_btint_a(52) <= \<const0>\;
  combined_operations_result_u_btint_a(51) <= \<const0>\;
  combined_operations_result_u_btint_a(50) <= \<const0>\;
  combined_operations_result_u_btint_a(49) <= \<const0>\;
  combined_operations_result_u_btint_a(48) <= \<const0>\;
  combined_operations_result_u_btint_a(47) <= \<const0>\;
  combined_operations_result_u_btint_a(46) <= \<const0>\;
  combined_operations_result_u_btint_a(45) <= \<const0>\;
  combined_operations_result_u_btint_a(44) <= \<const0>\;
  combined_operations_result_u_btint_a(43) <= \<const0>\;
  combined_operations_result_u_btint_a(42) <= \<const0>\;
  combined_operations_result_u_btint_a(41) <= \<const0>\;
  combined_operations_result_u_btint_a(40) <= \<const0>\;
  combined_operations_result_u_btint_a(39) <= \<const0>\;
  combined_operations_result_u_btint_a(38) <= \<const0>\;
  combined_operations_result_u_btint_a(37) <= \<const0>\;
  combined_operations_result_u_btint_a(36) <= \<const0>\;
  combined_operations_result_u_btint_a(35) <= \<const0>\;
  combined_operations_result_u_btint_a(34) <= \<const0>\;
  combined_operations_result_u_btint_a(33) <= \<const0>\;
  combined_operations_result_u_btint_a(32) <= \<const0>\;
  combined_operations_result_u_btint_a(31) <= \<const0>\;
  combined_operations_result_u_btint_a(30) <= \<const0>\;
  combined_operations_result_u_btint_a(29) <= \<const0>\;
  combined_operations_result_u_btint_a(28) <= \<const0>\;
  combined_operations_result_u_btint_a(27) <= \<const0>\;
  combined_operations_result_u_btint_a(26) <= \<const0>\;
  combined_operations_result_u_btint_a(25) <= \<const0>\;
  combined_operations_result_u_btint_a(24) <= \<const0>\;
  combined_operations_result_u_btint_a(23) <= \<const0>\;
  combined_operations_result_u_btint_a(22) <= \<const0>\;
  combined_operations_result_u_btint_a(21) <= \<const0>\;
  combined_operations_result_u_btint_a(20) <= \<const0>\;
  combined_operations_result_u_btint_a(19) <= \<const0>\;
  combined_operations_result_u_btint_a(18) <= \<const0>\;
  combined_operations_result_u_btint_a(17) <= \<const0>\;
  combined_operations_result_u_btint_a(16) <= \<const0>\;
  combined_operations_result_u_btint_a(15) <= \<const0>\;
  combined_operations_result_u_btint_a(14) <= \<const0>\;
  combined_operations_result_u_btint_a(13) <= \<const0>\;
  combined_operations_result_u_btint_a(12) <= \<const0>\;
  combined_operations_result_u_btint_a(11) <= \<const0>\;
  combined_operations_result_u_btint_a(10) <= \<const0>\;
  combined_operations_result_u_btint_a(9) <= \<const0>\;
  combined_operations_result_u_btint_a(8) <= \<const0>\;
  combined_operations_result_u_btint_a(7) <= \<const0>\;
  combined_operations_result_u_btint_a(6) <= \<const0>\;
  combined_operations_result_u_btint_a(5) <= \<const0>\;
  combined_operations_result_u_btint_a(4) <= \<const0>\;
  combined_operations_result_u_btint_a(3) <= \<const0>\;
  combined_operations_result_u_btint_a(2) <= \<const0>\;
  combined_operations_result_u_btint_a(1) <= \<const0>\;
  combined_operations_result_u_btint_a(0) <= \<const0>\;
  combined_operations_result_u_btint_b(127) <= \<const0>\;
  combined_operations_result_u_btint_b(126) <= \<const0>\;
  combined_operations_result_u_btint_b(125) <= \<const0>\;
  combined_operations_result_u_btint_b(124) <= \<const0>\;
  combined_operations_result_u_btint_b(123) <= \<const0>\;
  combined_operations_result_u_btint_b(122) <= \<const0>\;
  combined_operations_result_u_btint_b(121) <= \<const0>\;
  combined_operations_result_u_btint_b(120) <= \<const0>\;
  combined_operations_result_u_btint_b(119) <= \<const0>\;
  combined_operations_result_u_btint_b(118) <= \<const0>\;
  combined_operations_result_u_btint_b(117) <= \<const0>\;
  combined_operations_result_u_btint_b(116) <= \<const0>\;
  combined_operations_result_u_btint_b(115) <= \<const0>\;
  combined_operations_result_u_btint_b(114) <= \<const0>\;
  combined_operations_result_u_btint_b(113) <= \<const0>\;
  combined_operations_result_u_btint_b(112) <= \<const0>\;
  combined_operations_result_u_btint_b(111) <= \<const0>\;
  combined_operations_result_u_btint_b(110) <= \<const0>\;
  combined_operations_result_u_btint_b(109) <= \<const0>\;
  combined_operations_result_u_btint_b(108) <= \<const0>\;
  combined_operations_result_u_btint_b(107) <= \<const0>\;
  combined_operations_result_u_btint_b(106) <= \<const0>\;
  combined_operations_result_u_btint_b(105) <= \<const0>\;
  combined_operations_result_u_btint_b(104) <= \<const0>\;
  combined_operations_result_u_btint_b(103) <= \<const0>\;
  combined_operations_result_u_btint_b(102) <= \<const0>\;
  combined_operations_result_u_btint_b(101) <= \<const0>\;
  combined_operations_result_u_btint_b(100) <= \<const0>\;
  combined_operations_result_u_btint_b(99) <= \<const0>\;
  combined_operations_result_u_btint_b(98) <= \<const0>\;
  combined_operations_result_u_btint_b(97) <= \<const0>\;
  combined_operations_result_u_btint_b(96) <= \<const0>\;
  combined_operations_result_u_btint_b(95) <= \<const0>\;
  combined_operations_result_u_btint_b(94) <= \<const0>\;
  combined_operations_result_u_btint_b(93) <= \<const0>\;
  combined_operations_result_u_btint_b(92) <= \<const0>\;
  combined_operations_result_u_btint_b(91) <= \<const0>\;
  combined_operations_result_u_btint_b(90) <= \<const0>\;
  combined_operations_result_u_btint_b(89) <= \<const0>\;
  combined_operations_result_u_btint_b(88) <= \<const0>\;
  combined_operations_result_u_btint_b(87) <= \<const0>\;
  combined_operations_result_u_btint_b(86) <= \<const0>\;
  combined_operations_result_u_btint_b(85) <= \<const0>\;
  combined_operations_result_u_btint_b(84) <= \<const0>\;
  combined_operations_result_u_btint_b(83) <= \<const0>\;
  combined_operations_result_u_btint_b(82) <= \<const0>\;
  combined_operations_result_u_btint_b(81) <= \<const0>\;
  combined_operations_result_u_btint_b(80) <= \<const0>\;
  combined_operations_result_u_btint_b(79) <= \<const0>\;
  combined_operations_result_u_btint_b(78) <= \<const0>\;
  combined_operations_result_u_btint_b(77) <= \<const0>\;
  combined_operations_result_u_btint_b(76) <= \<const0>\;
  combined_operations_result_u_btint_b(75) <= \<const0>\;
  combined_operations_result_u_btint_b(74) <= \<const0>\;
  combined_operations_result_u_btint_b(73) <= \<const0>\;
  combined_operations_result_u_btint_b(72) <= \<const0>\;
  combined_operations_result_u_btint_b(71) <= \<const0>\;
  combined_operations_result_u_btint_b(70) <= \<const0>\;
  combined_operations_result_u_btint_b(69) <= \<const0>\;
  combined_operations_result_u_btint_b(68) <= \<const0>\;
  combined_operations_result_u_btint_b(67) <= \<const0>\;
  combined_operations_result_u_btint_b(66) <= \<const0>\;
  combined_operations_result_u_btint_b(65) <= \<const0>\;
  combined_operations_result_u_btint_b(64) <= \<const0>\;
  combined_operations_result_u_btint_b(63) <= \<const0>\;
  combined_operations_result_u_btint_b(62) <= \<const0>\;
  combined_operations_result_u_btint_b(61) <= \<const0>\;
  combined_operations_result_u_btint_b(60) <= \<const0>\;
  combined_operations_result_u_btint_b(59) <= \<const0>\;
  combined_operations_result_u_btint_b(58) <= \<const0>\;
  combined_operations_result_u_btint_b(57) <= \<const0>\;
  combined_operations_result_u_btint_b(56) <= \<const0>\;
  combined_operations_result_u_btint_b(55) <= \<const0>\;
  combined_operations_result_u_btint_b(54) <= \<const0>\;
  combined_operations_result_u_btint_b(53) <= \<const0>\;
  combined_operations_result_u_btint_b(52) <= \<const0>\;
  combined_operations_result_u_btint_b(51) <= \<const0>\;
  combined_operations_result_u_btint_b(50) <= \<const0>\;
  combined_operations_result_u_btint_b(49) <= \<const0>\;
  combined_operations_result_u_btint_b(48) <= \<const0>\;
  combined_operations_result_u_btint_b(47) <= \<const0>\;
  combined_operations_result_u_btint_b(46) <= \<const0>\;
  combined_operations_result_u_btint_b(45) <= \<const0>\;
  combined_operations_result_u_btint_b(44) <= \<const0>\;
  combined_operations_result_u_btint_b(43) <= \<const0>\;
  combined_operations_result_u_btint_b(42) <= \<const0>\;
  combined_operations_result_u_btint_b(41) <= \<const0>\;
  combined_operations_result_u_btint_b(40) <= \<const0>\;
  combined_operations_result_u_btint_b(39) <= \<const0>\;
  combined_operations_result_u_btint_b(38) <= \<const0>\;
  combined_operations_result_u_btint_b(37) <= \<const0>\;
  combined_operations_result_u_btint_b(36) <= \<const0>\;
  combined_operations_result_u_btint_b(35) <= \<const0>\;
  combined_operations_result_u_btint_b(34) <= \<const0>\;
  combined_operations_result_u_btint_b(33) <= \<const0>\;
  combined_operations_result_u_btint_b(32) <= \<const0>\;
  combined_operations_result_u_btint_b(31) <= \<const0>\;
  combined_operations_result_u_btint_b(30) <= \<const0>\;
  combined_operations_result_u_btint_b(29) <= \<const0>\;
  combined_operations_result_u_btint_b(28) <= \<const0>\;
  combined_operations_result_u_btint_b(27) <= \<const0>\;
  combined_operations_result_u_btint_b(26) <= \<const0>\;
  combined_operations_result_u_btint_b(25) <= \<const0>\;
  combined_operations_result_u_btint_b(24) <= \<const0>\;
  combined_operations_result_u_btint_b(23) <= \<const0>\;
  combined_operations_result_u_btint_b(22) <= \<const0>\;
  combined_operations_result_u_btint_b(21) <= \<const0>\;
  combined_operations_result_u_btint_b(20) <= \<const0>\;
  combined_operations_result_u_btint_b(19) <= \<const0>\;
  combined_operations_result_u_btint_b(18) <= \<const0>\;
  combined_operations_result_u_btint_b(17) <= \<const0>\;
  combined_operations_result_u_btint_b(16) <= \<const0>\;
  combined_operations_result_u_btint_b(15) <= \<const0>\;
  combined_operations_result_u_btint_b(14) <= \<const0>\;
  combined_operations_result_u_btint_b(13) <= \<const0>\;
  combined_operations_result_u_btint_b(12) <= \<const0>\;
  combined_operations_result_u_btint_b(11) <= \<const0>\;
  combined_operations_result_u_btint_b(10) <= \<const0>\;
  combined_operations_result_u_btint_b(9) <= \<const0>\;
  combined_operations_result_u_btint_b(8) <= \<const0>\;
  combined_operations_result_u_btint_b(7) <= \<const0>\;
  combined_operations_result_u_btint_b(6) <= \<const0>\;
  combined_operations_result_u_btint_b(5) <= \<const0>\;
  combined_operations_result_u_btint_b(4) <= \<const0>\;
  combined_operations_result_u_btint_b(3) <= \<const0>\;
  combined_operations_result_u_btint_b(2) <= \<const0>\;
  combined_operations_result_u_btint_b(1) <= \<const0>\;
  combined_operations_result_u_btint_b(0) <= \<const0>\;
  combined_operations_result_u_overflow(31) <= \<const0>\;
  combined_operations_result_u_overflow(30) <= \<const0>\;
  combined_operations_result_u_overflow(29) <= \<const0>\;
  combined_operations_result_u_overflow(28) <= \<const0>\;
  combined_operations_result_u_overflow(27) <= \<const0>\;
  combined_operations_result_u_overflow(26) <= \<const0>\;
  combined_operations_result_u_overflow(25) <= \<const0>\;
  combined_operations_result_u_overflow(24) <= \<const0>\;
  combined_operations_result_u_overflow(23) <= \<const0>\;
  combined_operations_result_u_overflow(22) <= \<const0>\;
  combined_operations_result_u_overflow(21) <= \<const0>\;
  combined_operations_result_u_overflow(20) <= \<const0>\;
  combined_operations_result_u_overflow(19) <= \<const0>\;
  combined_operations_result_u_overflow(18) <= \<const0>\;
  combined_operations_result_u_overflow(17) <= \<const0>\;
  combined_operations_result_u_overflow(16) <= \<const0>\;
  combined_operations_result_u_overflow(15) <= \<const0>\;
  combined_operations_result_u_overflow(14) <= \<const0>\;
  combined_operations_result_u_overflow(13) <= \<const0>\;
  combined_operations_result_u_overflow(12) <= \<const0>\;
  combined_operations_result_u_overflow(11) <= \<const0>\;
  combined_operations_result_u_overflow(10) <= \<const0>\;
  combined_operations_result_u_overflow(9) <= \<const0>\;
  combined_operations_result_u_overflow(8) <= \<const0>\;
  combined_operations_result_u_overflow(7) <= \<const0>\;
  combined_operations_result_u_overflow(6) <= \<const0>\;
  combined_operations_result_u_overflow(5) <= \<const0>\;
  combined_operations_result_u_overflow(4) <= \<const0>\;
  combined_operations_result_u_overflow(3) <= \<const0>\;
  combined_operations_result_u_overflow(2) <= \<const0>\;
  combined_operations_result_u_overflow(1) <= \<const0>\;
  combined_operations_result_u_overflow(0) <= \<const0>\;
GND: unisim.vcomponents.GND
     port map (
      G => \<const0>\
    );
VCC: unisim.vcomponents.VCC
     port map (
      P => \<const1>\
    );
end STRUCTURE;
